/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_Program.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_date_to_converter (XDR *xdrs, input_date_to_converter *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->day_converted))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->month_converted))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->year_converted))
		 return FALSE;
	return TRUE;
}
