/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_Program.h"

float *cosine_series_1_svc(inputs *argp, struct svc_req *rqstp)
{
static float  result;
float x_r=(argp->x*3.14159)/180;
printf("\nClient Is Requesting The Value Of Cos %d\n",argp->x);
   float t=1,res=1;
int i;int n=argp->n;
    for(i=1;i<=n;i++)
    {
        t=t*(-1)*x_r*x_r/(2*i*(2*i-1));
        res=res+t;
    }

printf("Server Is Replaying...\n");
printf("Cosine of %d is %f \n",argp->x,res);
printf("\nReplying...\n");
printf("\nReplied\n");
printf("================================== \n ");
result=res;
return &result;
}

int *date_converter_1_svc(input_date_to_converter *argp, struct svc_req *rqstp)
{
static int  result;
int gregorial_month_days_length[] = { 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31 };
int ethiopian_month_days_length[13] = { 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 5 };
int month_days_difference[12] = { 10, 10, 9, 9, 8, 7, 9, 8, 8, 7, 7, 9 };
int gregorian_month[12] = {9,10,11,12,1,2,3,4,5,6,7,8};
int ethiopian_month[13] = {1,2,3,4,5,6,7,8,9,10,11,12,13};

int i=0,month_conv,year, day,month, year_conv, day_conv, monthNumber, day_to_ret;
day=argp->day_converted;
month=argp->month_converted;
year=argp->year_converted;
printf("\nClient is Requesting Date Conversion ");
printf("\nConverting ");
printf("%d/%d/%d",day,month,year);
printf(" GC to EC \n");
    for (i = 0; i < 12; ++i) {
        if (gregorian_month[i] == month) {
            monthNumber = i + 1;
        }
    }
    int monthIndex,day_to_r;
    if (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) {
        for (i = 0; i < 12; ++i) {
            if (gregorian_month[i] == month) {
                monthIndex = i + 1;
            }
        }
            switch (monthIndex) {
            case 12:
                day_to_r = day - month_days_difference[monthIndex - 1];
            default:
                day_to_r = day - month_days_difference[monthIndex - 1];
            }
        }
    else {
            for (i = 0; i < 12; ++i) {
                if (gregorian_month[i] == month) {
                    monthIndex = i + 1;
                }
            }
        switch (monthIndex) {
        case 12:
            day_to_r = day - month_days_difference[monthIndex - 1];
        default:
            day_to_r = day - month_days_difference[monthIndex - 1];
        }
    }
    char gregorian_to_ethiopian [13];
    int day_f;
    if (day_to_r < 1) {
        for (i = 1; i <= 11; ++i) {
            gregorian_to_ethiopian[gregorian_month[i]] = ethiopian_month[i - 1];
        }
        for (i = 0; i < 12; ++i) {
            if (gregorian_month[i] == month) {
                monthNumber = i + 1;
            }
        }
        day_f = (gregorial_month_days_length[monthNumber - 1]) + day_to_r;
    }
    else if (day_to_r > 0 && day_to_r < 45) {
        day_f = day_to_r;
        for (i = 0; i <12; ++i) {
            gregorian_to_ethiopian[gregorian_month[i]] = ethiopian_month[i];
        }
    }
if(month==9){
   if(day<=10&&day>5){day_conv=(-1*((10-day)-5));
     month_conv = 13;year=year-1;}
else if(day<=5){year=year-1;day_conv =day_f;month_conv = 12;
}
else{
    month_conv = gregorian_to_ethiopian[month];
    day_conv =day_f;
}
}
else{
    month_conv = gregorian_to_ethiopian[month];
    day_conv =day_f;
}
    if (monthNumber >= 5 && monthNumber <= 12) {
        if (monthNumber == 1 && day <= 11) {
            year_conv=year - 8;
        }
        else {
            year_conv = year - 8;
        }
    }
    else {
        year_conv = year - 7;
    }  
    char days[20],months[20],years[40];
    char day_in[20] = "0";char mo_in[20] = "0";
if(day_conv<10){
sprintf(days, "%d", day_conv);
strcat(day_in, days);}
else{sprintf(day_in, "%d", day_conv);}
if(month_conv<10){
sprintf(months, "%d", month_conv);
strcat(mo_in, months);}
else{sprintf(mo_in, "%d", month_conv);} 
sprintf(years, "%d",year_conv); 
strcat(day_in, mo_in); 
strcat(day_in, years); 
result= atoi(day_in);
printf("\nReplying... "); 
printf("\nReplied \n");
printf("================================== \n ");
return &result; 
}

