/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_Program.h"
void cosine_prog_1(char *host,int a,int b);
void date_prog_1(char *host,int days,int months,int years);

//
//Main Function For The Client
//
int main (int argc, char *argv[])
{
	char *host;
        int choice,x,i;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
printf("\n  Well Come To RPC Programming \n ");
printf("=================================== \n ");
printf("\n     Select Your Choice \n ");
printf("=================================== \n ");
printf("\n Enter 1. To Calculate Cos(x) \n ");
printf("\n Enter 2. To Convert Date From Gregorian To Ethiopian Calendar \n ");
printf("\n Enter 3. To Exit\n ");
printf("\n Enter Your Choice :");
scanf("\n %d",&choice);
if (choice==1){ 
printf("\nEnter The Value of X in Degree :");
scanf("\n %d",&x);
printf("\nHow Many Iterations of The Series :");
scanf("\n %d",&i);
printf("\n");
cosine_prog_1 (host,x,i);
}
else if(choice==2)
{
int i=0,month_conv,year,day,month, year_conv, day_conv, monthNumber, day_to_ret;
char str[10];
printf("\nEnter the Gregorian Date To Be Convert Like This-> 21/6/2020 \n");
scanf("\n %s", str);
char *input_date[4];
input_date[i] = strtok(str,"/");

while(input_date[i]!=NULL)
{
   input_date[i+1] = strtok(NULL,"/");i=i+1;
}
  year = atoi(input_date[2]);
 month = atoi(input_date[1]);
   day = atoi(input_date[0]);
if(day>31 || day<=0){
printf("\n Day Must Be in B/n 1 and 31 \n ");
}
if(month>12 || month<=0){
printf("\n Month Must Be in B/n 1 and 12 \n ");
}
date_prog_1 (host,day,month,year);
}
else if(choice==2){printf("\n Connection Aborted \n ");exit(1);}
else{printf("\n Please Choose Only 1 or 2 \n ");}
printf("=============================\n ");
exit (0);
}

//
//Cosine Series Calculater Client Function
//
void cosine_prog_1(char *host,int a,int b) {
	CLIENT *clnt;
	float  *result_1;
	inputs  cosine_series_1_arg;
#ifndef	DEBUG
	clnt = clnt_create (host, COSINE_PROG, COSINE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	cosine_series_1_arg.x=a;
	cosine_series_1_arg.n=b;
	result_1 = cosine_series_1(&cosine_series_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else{
printf("From Server Result of cos(%d) is :%f\n",a,*result_1);
}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

//
//The Following Function is client function for converting date
//
void date_prog_1(char *host,int days,int months,int years)
{
	CLIENT *clnt;
	int  *result_1;
	input_date_to_converter  date_converter_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DATE_PROG, DATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

date_converter_1_arg.day_converted=days;
date_converter_1_arg.month_converted=months;
date_converter_1_arg.year_converted=years;
result_1 = date_converter_1(&date_converter_1_arg, clnt);

	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else{
//The Following Code is To Format The OUTPUT to the client 
//It Has Nothing to do with the conversion
    printf("\nIn Ethiopian Calendar The Date Is :");
    int var=*result_1;
    int i,length,NumberToSplit1,NumberToSplit2,NumberToSplit3;
    char getStr[100];
    sprintf(getStr, "%d", var); 
    length = strlen(getStr);
    if(length<8){NumberToSplit1=1;NumberToSplit2=2;NumberToSplit3=4;}
    else{NumberToSplit1=2, NumberToSplit2=2, NumberToSplit3=4;}     
    for (i = 0; i < NumberToSplit1; i++) {
        printf("%c", getStr[i]);}
        printf("/");
    for (i = NumberToSplit1; i < (NumberToSplit1+NumberToSplit2); i++) {
        printf("%c", getStr[i]);}
        printf("/");
    for (i = (NumberToSplit1+NumberToSplit2); i < (NumberToSplit1+NumberToSplit2+NumberToSplit3); i++) {
        printf("%c", getStr[i]);}
        printf(" E.C\n\n");
}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}





