/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_PROGRAM_H_RPCGEN
#define _RPC_PROGRAM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int x;
	int n;
};
typedef struct inputs inputs;

struct input_date_to_converter {
	int day_converted;
	int month_converted;
	int year_converted;
};
typedef struct input_date_to_converter input_date_to_converter;

#define COSINE_PROG 0x12345678
#define COSINE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define cosine_series 1
extern  float * cosine_series_1(inputs *, CLIENT *);
extern  float * cosine_series_1_svc(inputs *, struct svc_req *);
extern int cosine_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cosine_series 1
extern  float * cosine_series_1();
extern  float * cosine_series_1_svc();
extern int cosine_prog_1_freeresult ();
#endif /* K&R C */

#define DATE_PROG 0x1fffffff
#define DATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define date_converter 1
extern  int * date_converter_1(input_date_to_converter *, CLIENT *);
extern  int * date_converter_1_svc(input_date_to_converter *, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define date_converter 1
extern  int * date_converter_1();
extern  int * date_converter_1_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);
extern  bool_t xdr_input_date_to_converter (XDR *, input_date_to_converter*);

#else /* K&R C */
extern bool_t xdr_inputs ();
extern bool_t xdr_input_date_to_converter ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_PROGRAM_H_RPCGEN */
